services:
  psql:
    image: postgres:latest
    container_name: project-orders-psql
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - POSTGRES_PRIMARY_USER=postgres
      - POSTGRES_PRIMARY_PASSWORD=postgres
      - POSTGRES_DB=orders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_ROOT_PASSWORD=postgres
      - POSTGRES_PRIMARY_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/psql/data
      - ./db/seed:/tmp
volumes:
  db: